before:
  hooks:
    - go mod tidy

builds:
- 
  goos:
    - darwin
    - linux
  env:
  - CGO_ENABLED=0
  ldflags:
  - -X github.com/codefresh-io/merlin/cmd.version={{.Version}} -X github.com/codefresh-io/merlin/cmd.commit={{.Commit}} -X github.com/codefresh-io/merlin/cmd.date={{.Date}}

archives:
- 
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip


brews:
  -
    name: merlin
    tap:
      owner: codefresh-io
      name: homebrew-merlin

    commit_author:
      name: Oleg Sucharevich
      email: oleg2807@gmail.com 

    folder: Formula
    homepage: "http://docs.codefresh.io"
    description: "merlin --help"

    install: |
        bin.install "merlin"