version: '1.0'
mode: parallel
stages:
- Build & Test
steps:
  calculate_version:
    title: 'Calculate latest version'
    image: codefresh/cli
    commands:
        - export VERSION=$(cat VERSION)
        - cf_export VERSION
    when:
      steps:
      - name: main_clone
        on:
        - success
 
  build_binaries:
    title: Build binaries for all platforms - skip publish
    image: goreleaser/goreleaser
    stage: Build & Test
    fail_fast: false
    commands:
    - go mod download
    - goreleaser release -f .goreleaser.yml --rm-dist --skip-publish
    when:
      steps:
      - name: main_clone
      branch:
        ignore:
        - master

