version: '1.0'
mode: parallel
stages:
- Build & Test
steps:
  calculate_version:
    title: 'Calculate latest version'
    image: codefresh/cli
    commands:
        - export VERSION=$(cat VERSION)
        - cf_export VERSION
    when:
      steps:
      - name: main_clone
        on:
        - success
 
  create_git_tag:
    title: Push tag to git
    image: codefresh/cli
    stage: Release
    commands:
    - export OLD_ORIGIN=$(git remote get-url origin)
    - git remote rm origin
    - git remote add origin https://${{GITHUB_TOKEN}}@github.com/codefresh-io/merlin.git
    - git tag v${{VERSION}}
    - git push --tags
    - git remote rm origin
    - git remote add origin $OLD_ORIGIN
    
    fail_fast: false
    when:
      steps:
      - name: calculate_version
      - name: main_clone
      branch:
        only:
        - master

  build_binaries:
    title: Build binaries for all platforms - skip publish
    image: goreleaser/goreleaser
    stage: Build & Test
    fail_fast: false
    commands:
    - go mod download
    - goreleaser release -f .goreleaser.yml --rm-dist --skip-publish
    when:
      steps:
      - name: main_clone
      branch:
        ignore:
        - master

  release_binaries:
    title: Create release in Github with venona CLI
    image: goreleaser/goreleaser
    stage: Release
    fail_fast: false
    commands:
    - go mod download
    - goreleaser release -f .goreleaser.yml --rm-dist --skip-validate
    when:
      steps:
      - name: create_git_tag
        on:
        - finished
      branch:
        only:
        - master
